### ISSUE TITLE
Missing Dockerfile

### ISSUE THREAD

**Issue by thaJeztah** [ahmetalpbalkan/personal-dashboard#3]
Title says all ;-)

**Comment by ahmetalpbalkan** [comment]
Yeah it's accurate. I couldn't find a time to dockerize my apps yet. :-) I appreciate contribs :P

**Comment by thaJeztah** [comment]
:-)

**Comment by ahmetalpbalkan** [comment]
@thaJeztah Fixed. :wink:

**Comment by thaJeztah** [comment]
\o/
